server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      soundcloud: false
      bandcamp: false
      twitch: false
      vimeo: false
      mixer: false
      http: false
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    youtubeSearchPrefix: "ytsearch:"
    gc-warnings: true
